name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |  
  ## Previous release tag

  $PREVIOUS_TAG

  ## Changelog

  $CHANGES

  ## Full changelog

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Contributions

  $CONTRIBUTORS

  ## Repo

  $REPOSITORY

  ## Owner

  $OWNER
