name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |  
  ## Previous release tag

  $PREVIOUS_TAG

  ## Changelog

  $CHANGES

  ## Full changelog

  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Diff

  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...HEAD

  ## Contributions

  $CONTRIBUTORS

  ## Repo

  $REPOSITORY

  ## Owner

  $OWNER

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

# The above config controls the output of the $RESOLVED_VERSION variable.

# If a pull requests is found with the label major/minor/patch, the 
# corresponding version key will be incremented from a semantic version. 
# The maximum out of major, minor and patch found in any of the pull 
# requests will be used to increment the version number. 
# If no pull requests are found with the assigned labels, the default will be assigned.