name: test-github-dispatch-provider
on:
  repository_dispatch:
    types: [Helmrelease/poker.futrli]
jobs:
  run-tests-staging:
#    if: github.event.client_payload.metadata.summary == 'staging (eu-west-1)'
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
