name: "Confirm Deployment"

on:
  repository_dispatch:
    types: [ImageUpdateAutomation/poker.flux-system]

env:
  message: ${{ github.event.client_payload.message }}
  summary: ${{ github.event.client_payload.metadata.summary }}

jobs:
  confirm_deployment:
    name: confirm_deployment
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"

      - name: Docker tag
        id: docker_tag
        run: |
          if [ ${{ env.summary }} = "staging-eu-west-1" ]
          then
            docker_tag=$(echo -e "${{ github.event.client_payload.message }}" | grep -Eo "staging-.{7}-[0-9]+")
            echo docker_tag=$docker_tag >> $GITHUB_ENV
          fi

          if [ ${{ env.summary }} = "prod-eu-west-1" ]
          then
            docker_tag=$(echo -e "${{ github.event.client_payload.message }}" | grep -Eo "prod-.{7}-[0-9]+")
            echo docker_tag=$docker_tag >> $GITHUB_ENV
          fi

      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 89d9a7e5ace662c5600fd5357b1b2317
          filename: test.json # ${{ "github.event.client_payload.metadata.summary }}.json"
          label: ${{ env.summary }}
          message: "${{ env.docker_tag }}"
          color: "#2dba4e"
          namedLogo: Flux
          logoColor: white
          style: social