name: "Confirm Deployment"

on:
  repository_dispatch:
    types: [ImageUpdateAutomation/poker.flux-system]

env:
  message: ${{ github.event.client_payload.message }}
#   timestamp: ${{ github.event.client_payload.timestamp }}
#   kind: ${{ github.event.client_payload.involvedObject.kind }}
#   name: ${{ github.event.client_payload.involvedObject.name }}
  summary: ${{ github.event.client_payload.metadata.summary }}

jobs:
  confirm_deployment:
    name: confirm_deployment
    runs-on: ubuntu-latest
    steps:
      # - name: Display message
      #   run: |
      #     if ["$message" != "Helm upgrade succeeded"]
      #     then 
      #       echo "$message for $kind $name in environment $summary - $timestamp"
      #       exit 1
      #     else
      #       echo "$message for $kind $name in environment $summary - $timestamp"
      #     fi
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 89d9a7e5ace662c5600fd5357b1b2317
          filename: test.json
          label: ${{ github.event.client_payload.metadata.summary }}
          message: echo ${{ github.event.client_payload.message }} | egrep -Eo 'staging-.{7}-[0-9]+' 
          color: "#2dba4e"
          namedLogo: Flux
          logoColor: white
          style: social