name: test-github-dispatch-provider
on:
  repository_dispatch:
    types: [Kustomization/poker.futrli]
jobs:
  run-tests-staging:
#    if: github.event.client_payload.metadata.summary == 'staging (eu-west-1)'
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        echo "metadata: github.event.client_payload.metadata"
        echo "payload: github.event.client_payload"
