name: github-dispatch-provider

on:
  repository_dispatch:
    types: [HelmRelease/poker.futrli]

# env passed in from run

jobs:
  confirm_deployment:
  name: Confirm Deployment
# daz ni werk    if: ${{ (github.event.client_payload.message == 'Helm upgrade succeeded') && (github.event.client_payload.message.metadata.summary == 'staging eu-west-1) }}
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
