name: "Confirm Deployment"

on:
  repository_dispatch:
    types: [HelmRelease/poker.futrli]

jobs:
  confirm_deployment:
    name: confirm_deployment
    runs-on: ubuntu-latest
    steps:
    # - name: Dump GitHub context
    #   env:
    #     GITHUB_CONTEXT: ${{ toJson(github) }}
    #   run: |
    #     echo "$GITHUB_CONTEXT"

    - name: Display message
      env:
        message: ${{ github.event.client_payload.message }}
      run: |
        echo $message 
