# Package and deploy docker image
name: CI development

on:
  push:
    branches:    
      - 'development'

jobs:
  dockerimagereleaser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    # this is a simple way of using date and time to do versioning.
    - name: Modify scripts and get version
      id: version
      run: echo ::set-output name=date_version::$(date -u +'%Y%m%d%H%M%S')

    - name: Show short sha
      id: sha
      run: echo ::set-output name=short_sha::$(echo ${GITHUB_SHA::8})

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: ./src/Poker/yarn.lock

    - name: Install dependencies and build
      working-directory: ./src/Poker
      run: yarn --prefer-offline --frozen-lockfile

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          docker.io/seanmcguigan/poker:development-${{steps.sha.outputs.short_sha}}-${{steps.version.outputs.date_version}}
    
    - name: Check image been deployed to the development environment.
      run: echo "GitHub Dispatches"

    - name: Run tests in the development environment
      run: echo "Running integration tests"
      
