name: "Overnight build"

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  latest_commit_sha:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    # - name: set short git commit SHA
    #   id: vars
    #   run: |
    #     calculatedSha=$(git rev-parse --short ${{ github.sha }})
    #     echo "{SHORT_SHA}={$calculatedSha}" >> $GITHUB_OUTPUT

    - name: export calclatedSha
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "this is the calculated sha $calculatedSha"
        sed -i -E "/SHORT_SHA/s/[0-9a-zA-Z]{7}+$/$(git rev-parse --short ${{ github.sha }})/g" .github/variables/env
        echo "this is the content of the env file - $(cat .github/variables/env)" 

    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-set-variables@latest
      with:
        envFilePath: .github/variables/env
    
    - name: get env
      run: |
        env
