name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  short_sha:
    outputs: 
      short_sha: ${{ steps.short_sha.outputs.short_sha }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set short git commit SHA
        id: short_sha
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      - name: echo
        run: | 
          echo "Output ${{ steps.short_sha.outputs.short_sha }}"
  
  draft_release:
    needs: short_sha
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.short_sha.outputs.short_sha }}

      - name: draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: env
        run: |
          echo "The recorded short commit sha ${{ needs.short_sha.outputs.short_sha }}"

