name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  short_sha:
    outputs: 
      current_short_sha: ${{ steps.short_sha.outputs.short_sha }}
      previous_release_tag: ${{ steps.prod_tag.outputs.prod_tag }}
      new_release_tag: ${{ steps.bump_prod_tag.outputs.new_prod_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: get current commit sha @main
        id: short_sha
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      - name: get previous release tag
        id: prod_tag
        run: |
          prod_tag=$(gh release view --json tagName | jq --raw-output .tagName)
          echo "prod_tag=$prod_tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: increment tag version for next release
        id: calculate_prod_tag
        run: |
          let new_prod_tag=${{ steps.prod_tag.outputs.prod_tag }}+1
          echo "new_prod_tag=$new_prod_tag" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.calculate_prod_tag.outputs.new_prod_tag }}
        env:
          GH_TOKEN: ${{ github.token }}
          
      - name: echo
        run: | 
          echo "Output short sha ${{ steps.short_sha.outputs.short_sha }}"
          echo "Output current release tag ${{ steps.prod_tag.outputs.prod_tag }}"
          echo "Output new release tag ${{ steps.calculate_prod_tag.outputs.new_prod_tag }}"
  
  # release:
  #   needs: short_sha
  #   name: release
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: env
  #       run: |
  #         echo "The recorded short commit sha ${{ needs.short_sha.outputs.current_short_sha }}"
  #         echo "The current prod release tag ${{ needs.short_sha.outputs.previous_release_tag }}"
  #         echo "The new prod release tag ${{ needs.short_sha.outputs.new+release_tag }}"

  #     - name: checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: "0"

  #     # Create a release draft      
  #     - name: create draft
  #       run: |
  #         gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
  #         /repos/seanmcguigan/poker-app/releases \
  #         -f tag_name=${{ needs.short_sha.outputs.new+release_tag }} \
  #         -f target_commitish='main' \
  #         -f name=${{ needs.short_sha.outputs.new+release_tag }} \
  #         -f body='Description of the release' \
  #         -F draft=true \
  #         -F prerelease=false \
  #         -F generate_release_notes=false
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
