name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  latest_commit_sha:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set short git commit SHA
        id: short_commit_sha
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "{short_sha}={$calculatedSha}" >> $GITHUB_OUTPUT

      - name: echo
        run: | 
          echo ${{ steps.short_commit_sha.outputs }}
