name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  short_sha:
    outputs: 
      current_short_sha: ${{ steps.short_sha.outputs.short_sha }}
      previous_release_tag: ${{ steps.prod_tag.outputs.prod_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: get current commit sha @HEAD
        id: short_sha
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      - name: get previous release tag
        id: prod_tag
        run: |
          prod_tag=$(gh release view --json tagName | jq --raw-output .tagName)
          echo "prod_tag=$prod_tag" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: increment tag version for next release
        id: bump_prod_tag
        run: |
          new_prod_tag=$((++${{ steps.prod_tag.outputs.prod_tag }}))
          echo "new_prod_tag=$new_prod_tag" >> $GITHUB_OUTPUT

      - name: echo
        run: | 
          echo "Output ${{ steps.short_sha.outputs.short_sha }}"
          echo "Output ${{ steps.prod_tag.outputs.prod_tag }}"
          echo "Output ${{ steps.bump_prod_tag.outputs.new_prod_tag }}"
  
  # draft_release:
  #   needs: short_sha
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3

  #     - name: env
  #       run: |
  #         echo "The recorded short commit sha ${{ needs.short_sha.outputs.current_short_sha }}"
  #         echo "The current prod release tag ${{ needs.short_sha.outputs.current_prod_tag }}"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # release:
  #   needs: short_sha
  #   name: release
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: env
  #       run: |
  #         echo "The recorded short commit sha ${{ needs.short_sha.outputs.current_short_sha }}"
  #         echo "The current prod release tag ${{ needs.short_sha.outputs.previous_release_tag }}"

  #     - name: checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: "0"

  #     # Create a release draft      
  #     - name: create draft
  #       run: |
  #         gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
  #         /repos/seanmcguigan/poker-app/releases \
  #         -f tag_name='v0.2.2' \
  #         -f target_commitish='main' \
  #         -f name='v0.2.2' \
  #         -f body='Description of the release' \
  #         -F draft=true \
  #         -F prerelease=false \
  #         -F generate_release_notes=false
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
