name: "Overnight build"

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
  latest_commit_sha:
    runs-on: ubuntu-32
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"

    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-set-variables@latest
      with:
        envFilePath: .github/variables/env
