name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  SHORT_SHA: $(git rev-parse --short ${{ github.sha }})

jobs:
  latest_commit_sha:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: export short sha
      run: |
        env


