name: "Overnight build"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  short_sha:
    outputs: 
      current_short_sha: ${{ steps.short_sha.outputs.short_sha }}
      current_prod_tag: ${{ steps.short_sha.outputs.prod_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set short git commit SHA
        id: short_sha
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "Output current short sha - $short_sha"
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

          prod_tag=$( git describe --tags $(git rev-list --tags --max-count=1))
          echo "Output current production release tag - $prod_tag"
          echo "prod_tag=$prod_tag" >> $GITHUB_OUTPUT

      - name: echo
        run: | 
          echo "Output ${{ steps.short_sha.outputs.short_sha }}"
          echo "Output ${{ steps.short_sha.outputs.prod_tag }}"
  
  draft_release:
    needs: short_sha
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: env
        run: |
          echo "The recorded short commit sha ${{ needs.short_sha.outputs.short_sha }}"
          echo "The current prod release tag ${{ needs.short_sha.outputs.short_sha }}"
