# Test PRs and optionally tag for deployment.
name: pull request validation

on:
  pull_request:
    branches:
      - main

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  dockerimageeleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Allow dockerimageeleaser to access older tag information.
          fetch-depth: 0
      
      - name: linting
        run: echo "Runiing linting tests"

      - name: unit tests
        run: echo "Runiing unit tests"
      


