# Test PRs and optionally tag for deployment.
name: pull request validation

on:
  pull_request:
    branches:
      - development

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: linting
        run: echo "Runiing linting tests"

      - name: unit tests
        run: echo "Runiing unit tests"
      


