name: "Prod-Release"

on:
  workflow_dispatch:

env:
  APP: "skeleton-application-frontend"
  AWS_REGION: "eu-west-1"

jobs:
  docker_tag:
    name: Docker tag for production and push to ECR.
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          date=$(date +%Y%m%d%H%M%S)
          echo date=$date >> $GITHUB_OUTPUT

      - name: Target release sha
        id: release_sha
        run: |
          release_sha=$(echo ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }} | grep -Eow "([a-f0-9]{7})")
          echo release_sha=$release_sha >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Outputs
        run: |
          echo sha: ${{ steps.release_sha.outputs.release_sha }}
          echo date ${{ steps.date.outputs.date }}
          echo pre-prod tag: ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }}
          

      - name: ECR prod tag
        uses: abronin/ecr-retag-action@v1
        with:
          repository: "futrli/${{ env.APP }}" # "${{ env.OWNER }}/${{ env.APP }}"
          tag: $(echo ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }})
          new-tags: "prod-${{ steps.release_sha.outputs.release_sha }}-${{ steps.date.outputs.date }}}"
