name: "Prod-Release"

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  APP: "skeleton-application-frontend"
  AWS_REGION: "eu-west-1"

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  docker_tag:
    name: Docker tag for production and push to ECR.
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Get current date
        id: date
        run: |
          date=$(date +%Y%m%d%H%M%S)
          echo date=$date >> $GITHUB_OUTPUT

      - name: Target release sha
        id: release_sha
        run: |
          release_sha=$(echo ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }} | grep -Eow "([a-f0-9]{7})")
          echo release_sha=$release_sha >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Outputs
        run: |
          echo sha: ${{ steps.release_sha.outputs.release_sha }}
          echo date ${{ steps.date.outputs.date }}
          echo pre-prod tag: ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }}

      - name: ECR prod tag
        uses: abronin/ecr-retag-action@v1
        env:
          LATEST_PRE_PROD_IMAGE_TAG: ${{ vars.LATEST_PRE_PROD_IMAGE_TAG }}
        with:
          repository: "futrli/${{ env.APP }}" # "${{ env.OWNER }}/${{ env.APP }}"
          tag: ${{ env.LATEST_PRE_PROD_IMAGE_TAG }}
          new-tags: "prod-${{ steps.release_sha.outputs.release_sha }}-${{ steps.date.outputs.date }}"
      
      # - name: sleep
      #   run: |
      #     sleep 360

      - name: Checkout
        uses: actions/checkout@v3

      - name: Wait for confirm_deployment to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.sha }}
#          check-name: confirm_deployment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 300
          running-workflow-name: wait-for-check-name

# github dispatches flux
# trigger confirm-deployment workflow to succeed with timeout