# Package and deploy docker image
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:  
  push:
    tags:
      - '*'

jobs:
  dockerimageeleaser:
    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v2

    # this is a simple way of using date and time to do versioning.
    -
      name: Modify scripts and get version
      id: version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output

    -
      name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    -
      name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
            uses: docker/setup-buildx-action@v2

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    # here you can do additional steps

    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          docker.io/seanmcguigan/poker:$RELEASE_VERSION
          docker.io/seanmcguigan/poker:${{steps.version.outputs.date_version}}