# Package and deploy docker image
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:  
  push:
    tags:
      - 'v*'

jobs:
  dockerimageeleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
              uses: docker/setup-buildx-action@v2
      
      - name: BuildX
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build -t docker.io/seanmcguigan/poker:foobar . -f Docker/Dockerfile
      
      # - name: login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: docker.io/seanmcguigan/poker:$RELEASE_VERSION
