name: "Deploy staging"

run-name: Build and push staging image by @${{ github.actor }}

# permissions:
#   id-token: write
#   contents: read

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./frontend

env:
  DEPLOY_ENV_NAME: staging
  DEPLOY_SVC_NAME: frontend_nginx
  IMAGE_REPO: 733817689695.dkr.ecr.eu-west-1.amazonaws.com/futrli/skeleton-application-frontend
  SERVICE_NAME: skeleton-application
  GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }} #'< wrong'
  AWS_REGION: eu-west-1

jobs:
  build_and_push_image:
    runs-on: ubuntu-32
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "{short_sha}={$calculatedSha}" >> $GITHUB_OUTPUT

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.11.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          provenance: false
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: |
            733817689695.dkr.ecr.eu-west-1.amazonaws.com/futrli/skeleton-application-frontend:gha-testing-${{ steps.vars.outputs.short_sha }}-${{ github.run_number }}
          cache-from: type=registry,ref=733817689695.dkr.ecr.eu-west-1.amazonaws.com/futrli/skeleton-application-frontend:latest
          cache-to: type=inline
          build-args: |
            GEMFURY_TOKEN=${{ env.GEMFURY_TOKEN }}
          secret-files: |
            "MY_SECRET=./secret.txt"  
